import type { Classroom } from '../../validation/classroom.js';

// Landing page / table of contents for the HTML export. Unlike the SCORM entry
// (which auto-redirects to the first scene), the HTML TOC is a real destination:
// the user opens index.html, sees the classroom title + scene list, and clicks
// into whichever slide they want.

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

const TOC_CSS = `
  body { font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif; max-width: 900px; margin: 0 auto; padding: 2rem; color: #1a1a1a; line-height: 1.6; background: #fafafa; }
  h1 { font-size: 2.25rem; margin: 0 0 0.5rem; color: #0a0a0a; }
  .subtitle { font-size: 1rem; color: #6a6a6a; margin: 0 0 2rem; }
  .meta { font-size: 0.875rem; color: #6a6a6a; margin-bottom: 2rem; padding: 0.75rem 1rem; background: #f3f3f3; border-radius: 6px; display: inline-block; }
  ol.scene-list { list-style: none; padding: 0; margin: 0; display: grid; grid-template-columns: 1fr; gap: 0.75rem; }
  ol.scene-list li { margin: 0; }
  ol.scene-list a { display: flex; align-items: baseline; gap: 0.75rem; padding: 1rem 1.25rem; background: #fff; border: 1px solid #e8e8e8; border-radius: 8px; text-decoration: none; color: #1a1a1a; transition: border-color 0.15s; }
  ol.scene-list a:hover { border-color: #b4b4b4; background: #fff; }
  ol.scene-list .num { font-variant-numeric: tabular-nums; color: #9a9a9a; font-size: 0.875rem; min-width: 2.25rem; }
  ol.scene-list .title { font-weight: 500; }
  footer { margin-top: 3rem; padding-top: 1.5rem; border-top: 1px solid #e0e0e0; font-size: 0.75rem; color: #9a9a9a; }
`;

export interface RenderTocOptions {
  classroom: Classroom;
  sceneHrefs: string[];  // in scene-order, same length as classroom.scenes
  language: string;
}

export function renderTocHtml(opts: RenderTocOptions): string {
  const { classroom, sceneHrefs, language } = opts;
  const scenes = [...classroom.scenes].sort((a, b) => a.order - b.order);

  const description = classroom.stage.description
    ? `<p class="subtitle">${escapeHtml(classroom.stage.description)}</p>`
    : '';

  const items = scenes
    .map((scene, i) => {
      const title = escapeHtml(scene.title?.trim() || `Slide ${i + 1}`);
      const href = escapeHtml(sceneHrefs[i]!);
      const num = String(i + 1).padStart(2, '0');
      return `    <li><a href="${href}"><span class="num">${num}</span><span class="title">${title}</span></a></li>`;
    })
    .join('\n');

  return `<!doctype html>
<html lang="${escapeHtml(language)}">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${escapeHtml(classroom.stage.name)}</title>
  <style>${TOC_CSS}</style>
</head>
<body>
  <h1>${escapeHtml(classroom.stage.name)}</h1>
  ${description}
  <p class="meta">${scenes.length} slide${scenes.length === 1 ? '' : 's'}</p>
  <ol class="scene-list">
${items}
  </ol>
  <footer>Generated by OpenMAIC exporter &middot; classroom id: ${escapeHtml(classroom.id)}</footer>
</body>
</html>`;
}
